---
title: "R Notebook"
output: html_notebook
---


```{r setup, message = FALSE}
library(Quandl)
library(dplyr)
library(xts)
library(lubridate)
library(forecast)
library(dygraphs)
```

```{r, include = TRUE, fig.width = 9.5}
ten_year_breakeven <- Quandl("FRED/T10YIE", type = "xts", collapse = "daily",  
                    start_date="2015-11-01", end_date="2016-12-31")

copper <- Quandl("LME/PR_CU", type = "xts", collapse = "daily",  
                    start_date="2015-11-01", end_date="2016-12-31")

gold <- Quandl("CHRIS/CME_GC1", type = "xts", collapse = "daily",  
                    start_date="2015-11-01", end_date="2016-12-31")

combined <- merge.xts(ten_year_breakeven, copper$`Cash Buyer`)

dygraph(combined) %>% #dySeries("ten_year_breakeven") %>% dySeries("Cash.Buyer")
  dyRoller(rollPeriod = 3) %>% 
  dyAxis("y", label = "Percent (%)") %>%
  dyAxis("y2", label = "USD", independentTicks = TRUE) %>%
  dySeries("ten_year_breakeven", axis = 'y', label = "10 Year US Breakeven (LHS)") %>% 
  dySeries("Cash.Buyer", axis = 'y2', label = "Copper Spot Price (RHS)")

```
 


```{r, include = TRUE, fig.width = 9.5}

copper <- Quandl("CHRIS/CME_HG1", type = "xts", collapse = "daily",  
                    start_date="2012-01-01", end_date="2016-12-31")

gold <- Quandl("CHRIS/CME_GC1", type = "xts", collapse = "daily",  
                    start_date="2012-01-01", end_date="2016-12-31")

ten_year <- Quandl("FRED/DGS10", type = "xts", collapse = "daily",  
                    start_date="2012-01-01", end_date="2016-12-31")

ratio <- window(na.locf(merge(copper$Settle, gold$Settle, ten_year), formLast = TRUE), index(copper))
colnames(ratio) <- c("Copper", "Gold", "TenYear")
ratio$ratio <- (ratio$Copper*100)/ratio$Gold
ratio <- merge(ratio$ratio, ratio$TenYear)

dygraph(ratio) %>% 
  dyRoller(rollPeriod = 3) %>% 
  dyAxis("y", label = "Percent (%)") %>%
  dyAxis("y2", label = "USD", independentTicks = TRUE) %>%
  dySeries("ratio", axis = 'y', label = "Copper/Gold (LHS)") %>% 
  dySeries("TenYear", axis = 'y2', label = "10 Year (RHS)")
```
Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
